casemgmt:
  engine:
    mode: remote
    remote:
      base-url: ${CASEMGMT_ENGINE_REMOTE_BASE_URL}
      auth-mode: ${CASEMGMT_ENGINE_REMOTE_AUTH_MODE:basic}
      username: ${CASEMGMT_ENGINE_REMOTE_USERNAME:admin}
      password: ${CASEMGMT_ENGINE_REMOTE_PASSWORD:admin}
