-- Runs once on first container start (gvenzl images execute /container-entrypoint-initdb.d).
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER cm IDENTIFIED BY cm QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO cm;

CREATE USER operaton IDENTIFIED BY operaton QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO operaton;
