-- Runs on every container start from /container-entrypoint-startdb.d. Keep this script
-- idempotent: a developer may restart after an interrupted first database initialization.
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
    user_count PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO user_count FROM DBA_USERS WHERE USERNAME = 'CM';
    IF user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER cm IDENTIFIED BY cm QUOTA UNLIMITED ON USERS';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER cm IDENTIFIED BY cm ACCOUNT UNLOCK';
        EXECUTE IMMEDIATE 'ALTER USER cm QUOTA UNLIMITED ON USERS';
    END IF;
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW TO cm';

    SELECT COUNT(*) INTO user_count FROM DBA_USERS WHERE USERNAME = 'OPERATON';
    IF user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER operaton IDENTIFIED BY operaton QUOTA UNLIMITED ON USERS';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER operaton IDENTIFIED BY operaton ACCOUNT UNLOCK';
        EXECUTE IMMEDIATE 'ALTER USER operaton QUOTA UNLIMITED ON USERS';
    END IF;
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO operaton';
END;
/
