-- H2-only minimal expansion for the combined engine/platform transaction test. Production
-- migration correctness remains covered by the Oracle migration suite.

ALTER TABLE CM_CASE_DEF ADD ORCHESTRATION_MODE_ VARCHAR2(20) DEFAULT 'BPMN' NOT NULL;

CREATE TABLE CM_CASE_DEF_RELEASE (
  ID_ VARCHAR2(96) PRIMARY KEY,
  CASE_DEF_KEY_ VARCHAR2(255) NOT NULL,
  TENANT_ID_ VARCHAR2(64),
  KIND_ VARCHAR2(30) NOT NULL,
  MEDIA_TYPE_ VARCHAR2(128) NOT NULL,
  CONTENT_ BLOB NOT NULL,
  SHA256_ VARCHAR2(64) NOT NULL,
  STATUS_ VARCHAR2(20) NOT NULL,
  ENGINE_DEPLOYMENT_ID_ VARCHAR2(128),
  ENGINE_PROC_DEF_ID_ VARCHAR2(128),
  ENGINE_PROC_DEF_KEY_ VARCHAR2(255),
  ENGINE_PROC_DEF_VER_ NUMBER(10),
  ENGINE_TENANT_ID_ VARCHAR2(64),
  FAILURE_DETAIL_ VARCHAR2(2000),
  PUBLISHED_AT_ TIMESTAMP WITH TIME ZONE NOT NULL,
  VALIDATED_AT_ TIMESTAMP WITH TIME ZONE,
  ACTIVATED_AT_ TIMESTAMP WITH TIME ZONE,
  RETIRED_AT_ TIMESTAMP WITH TIME ZONE,
  PUBLISHED_BY_ VARCHAR2(255) NOT NULL
);

CREATE TABLE CM_CASE_DEF_BINDING (
  CASE_DEF_ID_ VARCHAR2(64) PRIMARY KEY,
  CASE_DEF_KEY_ VARCHAR2(255) NOT NULL,
  TENANT_ID_ VARCHAR2(64),
  ORCH_RELEASE_ID_ VARCHAR2(96) NOT NULL,
  ORCH_SHA256_ VARCHAR2(64) NOT NULL,
  CONTRACT_RELEASE_ID_ VARCHAR2(96) NOT NULL,
  CONTRACT_SHA256_ VARCHAR2(64) NOT NULL,
  PRESENT_RELEASE_ID_ VARCHAR2(96) NOT NULL,
  PRESENT_SHA256_ VARCHAR2(64) NOT NULL,
  DEPLOY_STATUS_ VARCHAR2(20) NOT NULL,
  ORCHESTRATION_MODE_ VARCHAR2(20) NOT NULL,
  STATUS_ VARCHAR2(20) NOT NULL,
  ENGINE_DEPLOYMENT_ID_ VARCHAR2(128),
  ENGINE_PROC_DEF_ID_ VARCHAR2(128),
  ENGINE_PROC_DEF_KEY_ VARCHAR2(255),
  ENGINE_PROC_DEF_VER_ NUMBER(10),
  ENGINE_TENANT_ID_ VARCHAR2(64),
  FAILURE_DETAIL_ VARCHAR2(2000),
  BOUND_AT_ TIMESTAMP WITH TIME ZONE NOT NULL,
  ACTIVATED_AT_ TIMESTAMP WITH TIME ZONE,
  RETIRED_AT_ TIMESTAMP WITH TIME ZONE,
  BOUND_BY_ VARCHAR2(255) NOT NULL
);

CREATE UNIQUE INDEX UQ_TEST_ACTIVE_BINDING
  ON CM_CASE_DEF_BINDING(CASE_DEF_KEY_, TENANT_ID_, STATUS_);

ALTER TABLE CM_CASE ADD ROOT_PROC_INST_ID_ VARCHAR2(128);
ALTER TABLE CM_CASE ADD ROOT_CORRELATION_ID_ VARCHAR2(128);
ALTER TABLE CM_CASE ADD PROJECTION_STATUS_ VARCHAR2(20) DEFAULT 'CURRENT' NOT NULL;
ALTER TABLE CM_CASE ADD LAST_ENGINE_UPDATE_AT_ TIMESTAMP WITH TIME ZONE;
ALTER TABLE CM_CASE ADD LAST_PROJECTED_AT_ TIMESTAMP WITH TIME ZONE;

ALTER TABLE CM_PLAN_ITEM ALTER COLUMN PROC_INST_ID_ VARCHAR2(128);
ALTER TABLE CM_PLAN_ITEM ADD ENGINE_ACTIVITY_ID_ VARCHAR2(128);
ALTER TABLE CM_PLAN_ITEM ADD PROJECTION_STATUS_ VARCHAR2(20) DEFAULT 'CURRENT' NOT NULL;
ALTER TABLE CM_PLAN_ITEM ADD LAST_ENGINE_UPDATE_AT_ TIMESTAMP WITH TIME ZONE;
ALTER TABLE CM_PLAN_ITEM ADD LAST_PROJECTED_AT_ TIMESTAMP WITH TIME ZONE;
CREATE UNIQUE INDEX UQ_TEST_PLAN_ENGINE_ACTIVITY ON CM_PLAN_ITEM(ENGINE_ACTIVITY_ID_);

ALTER TABLE CM_TASK ADD ENGINE_SYNC_ VARCHAR2(20) DEFAULT 'SYNCED' NOT NULL;
ALTER TABLE CM_TASK ADD PROC_INST_ID_ VARCHAR2(128);
ALTER TABLE CM_TASK ADD PROJECTION_STATUS_ VARCHAR2(20) DEFAULT 'CURRENT' NOT NULL;
ALTER TABLE CM_TASK ADD LAST_ENGINE_UPDATE_AT_ TIMESTAMP WITH TIME ZONE;
ALTER TABLE CM_TASK ADD LAST_PROJECTED_AT_ TIMESTAMP WITH TIME ZONE;
CREATE UNIQUE INDEX UQ_TEST_TASK_ENGINE_ID ON CM_TASK(CAMUNDA_TASK_ID_);

ALTER TABLE CM_LINKED_PROCESS ALTER COLUMN PROC_INST_ID_ DROP NOT NULL;
ALTER TABLE CM_LINKED_PROCESS ADD CORRELATION_ID_ VARCHAR2(128);
ALTER TABLE CM_LINKED_PROCESS ADD PROC_DEF_ID_ VARCHAR2(128);
ALTER TABLE CM_LINKED_PROCESS ADD IS_CASE_ROOT_ NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE CM_LINKED_PROCESS ADD ENGINE_SYNC_ VARCHAR2(20) DEFAULT 'SYNCED' NOT NULL;
ALTER TABLE CM_LINKED_PROCESS ADD PROJECTION_STATUS_ VARCHAR2(20) DEFAULT 'CURRENT' NOT NULL;
ALTER TABLE CM_LINKED_PROCESS ADD LAST_ENGINE_UPDATE_AT_ TIMESTAMP WITH TIME ZONE;
ALTER TABLE CM_LINKED_PROCESS ADD LAST_PROJECTED_AT_ TIMESTAMP WITH TIME ZONE;
CREATE UNIQUE INDEX UQ_TEST_LINK_CORRELATION ON CM_LINKED_PROCESS(CORRELATION_ID_);

CREATE TABLE CM_EVENT_APPEND_LOCK (LOCK_NAME_ VARCHAR2(64) PRIMARY KEY);
INSERT INTO CM_EVENT_APPEND_LOCK(LOCK_NAME_) VALUES ('default');

CREATE TABLE CM_APPLIED_ENGINE_OBSERVATION (
  OBSERVATION_ID_ VARCHAR2(128) NOT NULL,
  TENANT_ID_ VARCHAR2(64),
  FINGERPRINT_ VARCHAR2(64) NOT NULL,
  CLAIM_TOKEN_ VARCHAR2(43) NOT NULL,
  STATUS_ VARCHAR2(16) NOT NULL,
  SOURCE_ VARCHAR2(128) NOT NULL,
  ENGINE_ID_ VARCHAR2(128),
  CASE_ID_ VARCHAR2(128) NOT NULL,
  PROCESS_INSTANCE_ID_ VARCHAR2(128) NOT NULL,
  OBSERVATION_KIND_ VARCHAR2(32) NOT NULL,
  ENTITY_ID_ VARCHAR2(128) NOT NULL,
  ENTITY_REVISION_ NUMBER(19),
  EVENT_TYPE_ VARCHAR2(64) NOT NULL,
  ENGINE_OCCURRED_AT_ TIMESTAMP WITH TIME ZONE NOT NULL,
  CLAIMED_AT_ TIMESTAMP WITH TIME ZONE NOT NULL,
  APPLIED_AT_ TIMESTAMP WITH TIME ZONE,
  IGNORED_AT_ TIMESTAMP WITH TIME ZONE,
  FAILED_AT_ TIMESTAMP WITH TIME ZONE,
  FAILURE_DETAIL_ VARCHAR2(2000)
);
CREATE UNIQUE INDEX UQ_TEST_OBSERVATION_FINGERPRINT
  ON CM_APPLIED_ENGINE_OBSERVATION(TENANT_ID_, FINGERPRINT_);
